version: '3.8'

services:
  django-db:
    image: postgres:latest
    platform: linux/amd64
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=djangodb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: "exit 0"

  django-pgadmin:
    image: dpage/pgadmin4:latest
    platform: linux/amd64
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@test.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - "8080:8080"
    links:
      - "django-db:pgsql-server"
    depends_on:
      django-db:
        condition: service_healthy

  django-api:
    build: ./djangoAPI
    command: bash -c "
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000"
    restart: on-failure
    volumes:
      - ./djangoAPI:/djangoAPI
    ports:
      - "8000:8000"
    env_file:
      - .envs/env.development
    depends_on: 
      django-db:
        condition: service_healthy

volumes:
  pg-data:
  pgadmin-data:
